sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - gcc-7
            - g++-7
            - cmake
            - cmake-data
            - git
            - build-essential
            - checkinstall
            - pkg-config
            - yasm
            - gfortran
            - software-properties-common
            - libjpeg8-dev
            - libjasper-dev
            - libpng12-dev
            - libtiff5-dev
            - libavcodec-dev
            - libavformat-dev
            - libswscale-dev
            - libdc1394-22-dev
            - libxine2-dev
            - libv4l-dev
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - libgtk2.0-dev
            - libtbb-dev
            - qt5-default
            - libatlas-base-dev
            - libfaac-dev
            - libmp3lame-dev
            - libtheora-dev
            - libvorbis-dev
            - libxvidcore-dev
            - libopencore-amrnb-dev
            - libopencore-amrwb-dev
            - libavresample-dev
            - x264 
            - v4l-utils
      env: COMPILER=g++-7
#For OpenCV installation
before_script:
  - git clone https://github.com/opencv/opencv.git
  # - git clone https://github.com/opencv/opencv_contrib.git

  - cd opencv
  - git checkout 4.4.0
  - cd ..
  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv_contrib
  - git checkout 4.4.0
  - cd ..
  - sudo cp -r opencv_contrib/modules/tracking/ opencv/modules
  - cd opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_C_EXAMPLES=OFF \
    -D INSTALL_PYTHON_EXAMPLES=OFF \
    -D WITH_TBB=ON \
    -D WITH_V4L=ON \
    -D WITH_QT=ON \
    -D WITH_OPENGL=ON \
    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
    -D BUILD_EXAMPLES=OFF ..

  - make -j$(nproc)
  - sudo make install
  - sudo sh -c "echo '/usr/local/lib' >> /etc/ld.so.conf.d/opencv.conf"
  - sudo ldconfig

  - cd ../../
  - sudo cp -r opencv_contrib/modules/tracking/include/opencv2/tracking /usr/local/include/opencv4/opencv2/
  - echo "OpenCV installation DONE!"
before_install:
  - pip install --user cpp-coveralls
  - sudo -H pip install --upgrade requests[security] 
install:
  - sudo apt-get install -y -qq lcov
script:
  - bash requirements.sh
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - cd /usr/local/include/opencv4/opencv2/
  - ls
  - cd /usr/include/opencv2/
  - ls
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
